package com.kailang.engasst.pojo;

public class Sentence {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.USERNO
     *
     * @mbg.generated
     */
    private Integer userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.SNO
     *
     * @mbg.generated
     */
    private Integer sno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.EN
     *
     * @mbg.generated
     */
    private String en;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.CN
     *
     * @mbg.generated
     */
    private String cn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.USERNO
     *
     * @return the value of SENTENCE.USERNO
     *
     * @mbg.generated
     */
    public Integer getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.USERNO
     *
     * @param userno the value for SENTENCE.USERNO
     *
     * @mbg.generated
     */
    public void setUserno(Integer userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.SNO
     *
     * @return the value of SENTENCE.SNO
     *
     * @mbg.generated
     */
    public Integer getSno() {
        return sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.SNO
     *
     * @param sno the value for SENTENCE.SNO
     *
     * @mbg.generated
     */
    public void setSno(Integer sno) {
        this.sno = sno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.EN
     *
     * @return the value of SENTENCE.EN
     *
     * @mbg.generated
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.EN
     *
     * @param en the value for SENTENCE.EN
     *
     * @mbg.generated
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.CN
     *
     * @return the value of SENTENCE.CN
     *
     * @mbg.generated
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.CN
     *
     * @param cn the value for SENTENCE.CN
     *
     * @mbg.generated
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }
}