package com.kailang.engasst.dao;

import com.kailang.engasst.pojo.Sentence;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SentenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SENTENCE
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userno") Integer userno, @Param("sno") Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SENTENCE
     *
     * @mbg.generated
     */
    int insert(Sentence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SENTENCE
     *
     * @mbg.generated
     */
    Sentence selectByPrimaryKey(@Param("userno") Integer userno, @Param("sno") Integer sno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SENTENCE
     *
     * @mbg.generated
     */
    List<Sentence> selectAll(@Param("userno") Integer userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SENTENCE
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Sentence record);
}