package com.kailang.engasst.dao;

import com.kailang.engasst.pojo.User;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Integer userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CUSTOMER
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);

    /**
     * 根据用户名和密码查询
     * */
    User findByUsernameAndPassword(@Param("userno") Integer userno, @Param("password") String password);

    /**
     * 判断用户名是否存在
     *
     * */

    Integer findByUsername(@Param("userno") Integer userno);
}