package com.kailang.engasst.dao;

import com.kailang.engasst.pojo.Word;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface WordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORD
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("userno") Integer userno, @Param("wno") Integer wno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORD
     *
     * @mbg.generated
     */
    int insert(Word record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORD
     *
     * @mbg.generated
     */
    Word selectByPrimaryKey(@Param("userno") Integer userno, @Param("wno") Integer wno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORD
     *
     * @mbg.generated
     */
    List<Word> selectAll(@Param("userno") Integer userno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORD
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Word record);
}