package com.kailang.engasst.dao;

import com.kailang.engasst.pojo.Wordlib;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface WordlibMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORDLIB
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer wno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORDLIB
     *
     * @mbg.generated
     */
    int insert(Wordlib record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORDLIB
     *
     * @mbg.generated
     */
    Wordlib selectByPrimaryKey(Integer wno);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORDLIB
     *
     * @mbg.generated
     */
    List<Wordlib> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table WORDLIB
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Wordlib record);

    List<Wordlib> selectByLevel(@Param("wlevel") short wlevel);
}