package com.kailang.engasst.vo;

import java.math.BigDecimal;

public class LibraryVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIBRARY.NO
     *
     * @mbg.generated
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIBRARY.WLEVEL
     *
     * @mbg.generated
     */
    private BigDecimal wlevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIBRARY.EN
     *
     * @mbg.generated
     */
    private String en;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIBRARY.CN
     *
     * @mbg.generated
     */
    private String cn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIBRARY.NO
     *
     * @return the value of LIBRARY.NO
     *
     * @mbg.generated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIBRARY.NO
     *
     * @param no the value for LIBRARY.NO
     *
     * @mbg.generated
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIBRARY.WLEVEL
     *
     * @return the value of LIBRARY.WLEVEL
     *
     * @mbg.generated
     */
    public BigDecimal getWlevel() {
        return wlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIBRARY.WLEVEL
     *
     * @param wlevel the value for LIBRARY.WLEVEL
     *
     * @mbg.generated
     */
    public void setWlevel(BigDecimal wlevel) {
        this.wlevel = wlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIBRARY.EN
     *
     * @return the value of LIBRARY.EN
     *
     * @mbg.generated
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIBRARY.EN
     *
     * @param en the value for LIBRARY.EN
     *
     * @mbg.generated
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIBRARY.CN
     *
     * @return the value of LIBRARY.CN
     *
     * @mbg.generated
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIBRARY.CN
     *
     * @param cn the value for LIBRARY.CN
     *
     * @mbg.generated
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }
}