package com.kailang.engasst.vo;

public class SentenceVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.USERNO
     *
     * @mbg.generated
     */
    private Integer userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.NO
     *
     * @mbg.generated
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.EN
     *
     * @mbg.generated
     */
    private String en;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SENTENCE.CN
     *
     * @mbg.generated
     */
    private String cn;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.USERNO
     *
     * @return the value of SENTENCE.USERNO
     *
     * @mbg.generated
     */
    public Integer getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.USERNO
     *
     * @param userno the value for SENTENCE.USERNO
     *
     * @mbg.generated
     */
    public void setUserno(Integer userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.NO
     *
     * @return the value of SENTENCE.NO
     *
     * @mbg.generated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.NO
     *
     * @param no the value for SENTENCE.NO
     *
     * @mbg.generated
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.EN
     *
     * @return the value of SENTENCE.EN
     *
     * @mbg.generated
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.EN
     *
     * @param en the value for SENTENCE.EN
     *
     * @mbg.generated
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SENTENCE.CN
     *
     * @return the value of SENTENCE.CN
     *
     * @mbg.generated
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SENTENCE.CN
     *
     * @param cn the value for SENTENCE.CN
     *
     * @mbg.generated
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }
}