package com.kailang.engasst.vo;

public class StatVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAT.USERNO
     *
     * @mbg.generated
     */
    private Integer userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAT.TODAY
     *
     * @mbg.generated
     */
    private Short today;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAT.TOTAL
     *
     * @mbg.generated
     */
    private Integer total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAT.ACTDAY
     *
     * @mbg.generated
     */
    private Integer actday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAT.USERNO
     *
     * @return the value of STAT.USERNO
     *
     * @mbg.generated
     */
    public Integer getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAT.USERNO
     *
     * @param userno the value for STAT.USERNO
     *
     * @mbg.generated
     */
    public void setUserno(Integer userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAT.TODAY
     *
     * @return the value of STAT.TODAY
     *
     * @mbg.generated
     */
    public Short getToday() {
        return today;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAT.TODAY
     *
     * @param today the value for STAT.TODAY
     *
     * @mbg.generated
     */
    public void setToday(Short today) {
        this.today = today;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAT.TOTAL
     *
     * @return the value of STAT.TOTAL
     *
     * @mbg.generated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAT.TOTAL
     *
     * @param total the value for STAT.TOTAL
     *
     * @mbg.generated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAT.ACTDAY
     *
     * @return the value of STAT.ACTDAY
     *
     * @mbg.generated
     */
    public Integer getActday() {
        return actday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAT.ACTDAY
     *
     * @param actday the value for STAT.ACTDAY
     *
     * @mbg.generated
     */
    public void setActday(Integer actday) {
        this.actday = actday;
    }
}