package com.kailang.engasst.vo;

public class WordVO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORD.USERNO
     *
     * @mbg.generated
     */
    private Integer userno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORD.NO
     *
     * @mbg.generated
     */
    private Integer no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORD.EN
     *
     * @mbg.generated
     */
    private String en;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORD.CN
     *
     * @mbg.generated
     */
    private String cn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column WORD.WLEVEL
     *
     * @mbg.generated
     */
    private Short wlevel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORD.USERNO
     *
     * @return the value of WORD.USERNO
     *
     * @mbg.generated
     */
    public Integer getUserno() {
        return userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORD.USERNO
     *
     * @param userno the value for WORD.USERNO
     *
     * @mbg.generated
     */
    public void setUserno(Integer userno) {
        this.userno = userno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORD.NO
     *
     * @return the value of WORD.NO
     *
     * @mbg.generated
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORD.NO
     *
     * @param no the value for WORD.NO
     *
     * @mbg.generated
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORD.EN
     *
     * @return the value of WORD.EN
     *
     * @mbg.generated
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORD.EN
     *
     * @param en the value for WORD.EN
     *
     * @mbg.generated
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORD.CN
     *
     * @return the value of WORD.CN
     *
     * @mbg.generated
     */
    public String getCn() {
        return cn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORD.CN
     *
     * @param cn the value for WORD.CN
     *
     * @mbg.generated
     */
    public void setCn(String cn) {
        this.cn = cn == null ? null : cn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column WORD.WLEVEL
     *
     * @return the value of WORD.WLEVEL
     *
     * @mbg.generated
     */
    public Short getWlevel() {
        return wlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column WORD.WLEVEL
     *
     * @param wlevel the value for WORD.WLEVEL
     *
     * @mbg.generated
     */
    public void setWlevel(Short wlevel) {
        this.wlevel = wlevel;
    }
}